{
    'name': 'Fastindo Project',
    'version': '19.0.1.0.2',
    'summary': 'Kustomisasi modul utama Fastindo',
    'description': 'Modul utama Fastindo — dimulai dengan fitur Kategori Diskon pelanggan.',
    'author': 'Fastindo',
    'category': 'Customization',
    'depends': [
        'base',
        'contacts',
        'uom',
        'product',
        'stock',
        'sale',
        'sale_management',
        'purchase',
        'mail',
    ],
    'data': [
        'security/ir.model.access.csv',
        'data/product_data.xml',
        'views/contact/discount_category_views.xml',
        'views/contact/res_partner_views.xml',
        'views/inventory/product_views.xml',
        'views/sale/sale_order_views.xml',
        'views/purchase/purchase_order_views.xml',
        'views/inventory/stock_picking_views.xml',
        'views/inventory/stock_package_views.xml',
        'report/packing_list_report_views.xml',
        'report/packing_list_templates.xml',
        'views/inventory/packing_dashboard_template.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'fastindo_project/static/src/scss/packing.scss',
            # OWL Packing Board
            'fastindo_project/static/src/owl/components/packing_board/packing_board.js',
            'fastindo_project/static/src/owl/components/packing_board/packing_board.xml',
            'fastindo_project/static/src/owl/components/packing_board/packing_board.scss',
            'fastindo_project/static/src/owl/widgets/packing_board_widget.js',
            'fastindo_project/static/src/owl/widgets/packing_board_widget.xml',
        ],
    },
    'post_init_hook': 'post_init_hook',
    'installable': True,
    'auto_install': False,
    'application': False,
    'license': 'LGPL-3',
}
